# L'objectif est de créer un dockerfile qui installe nano, iproute2 et iputils-ping sur une image nginx:1.19.0
# pour gagnger du temps
FROM nginx:1.19.0

RUN apt-get update && apt-get install -y nano iproute2 iputils-ping 





